/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AccessSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ApiFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaApiAudience": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaApiTokenIssuer": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaApiUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaModelId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FgaStoreId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RedisUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SignupEmailDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SignupEmailQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SmtpHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SmtpMail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SmtpName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SmtpPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SmtpReplyTo": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SmtpUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeProPriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeUltraPriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}